const ShopActionTypes = {
  FETCH_COLLECTONS_START: "FETCH_COLLECTONS_START",
  FETCH_COLLECTONS_SUCCESS: "FETCH_COLLECTONS_SUCCESS",
  FETCH_COLLECTONS_FAILURE: "FETCH_COLLECTONS_FAILURE"
};

export default ShopActionTypes;
